#!/bin/bash

# i typically hook this into tmux (see my dotfiles) to have it on a bind
# for set, and force reset.

mk-file() {
    echo "enter command to save to quickrun file..."
    read cmd
    echo "saving '$cmd' to .quickrun"
    echo $cmd > .quickrun
}

unset create_file

if ! [[ -e .quickrun ]]; then
    create_file=1
fi

if [[ $1 == "-f" ]]; then
    create_file=1
fi

if [[ -n $create_file ]]; then
    # create new file
    mk-file;
fi

cmd=`cat .quickrun`

# quickrun is either custom on one line, cmd on next, or a default runner,
# defined in /etc/quickrun or ~/.config/quickrun

eval $cmd
printf "<ENTER> to close..."
read
#mk-file
